# Data Preprocessing for Grant Application Success Prediction

In this notebook, we will preprocess the dataset to prepare it for analysis and modeling. We will perform the following steps:
1. Load the data
2. Select key columns
3. Handle missing values
4. Feature engineering
5. Feature scaling

## Step 1: Load the Data

First, we load the training and test datasets.

In [17]:
import pandas as pd

# Load the training and test datasets
train_df = pd.read_csv('data/unimelb_training.csv', low_memory=False)
test_df = pd.read_csv('data/unimelb_test.csv', low_memory=False)

# Display the first few rows of the training data
print("Training Data:")
print(train_df.head())
print("\nTest Data:")
print(test_df.head())

Training Data:
   Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1             1          NaN                 NaN
1                     2             1           2B                 10A
2                     3             1          29A                 10B
3                     4             1          40D                 10B
4                     5             0          59C                 10A

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     8/11/05     280199.0              100.0
1                               B    11/11/05     280103.0               30.0
2                               A    14/11/05     321004.0               60.0
3                               C    15/11/05     270602.0               50.0
4                               A    16/11/05     260500.0               34.0

   RFCD.Code.2  RFCD.Percentage.2  ...  Faculty.No..15  With.PHD.15  \
0          0.0                0.0  ...             NaN          NaN
1     280106.0               30.0  ...             NaN          NaN
2     321216.0               40.0  ...             NaN          NaN
3     320602.0               50.0  ...             NaN          NaN
4     280000.0               33.0  ...             NaN          NaN

   No..of.Years.in.Uni.at.Time.of.Grant.15  Number.of.Successful.Grant.15  \
0                                      NaN                            NaN
1                                      NaN                            NaN
2                                      NaN                            NaN
3                                      NaN                            NaN
4                                      NaN                            NaN

   Number.of.Unsuccessful.Grant.15  A..15  A.15  B.15  C.15  Unnamed: 251
0                              NaN    NaN   NaN   NaN   NaN           NaN
1                              NaN    NaN   NaN   NaN   NaN           NaN
2                              NaN    NaN   NaN   NaN   NaN           NaN
3                              NaN    NaN   NaN   NaN   NaN           NaN
4                              NaN    NaN   NaN   NaN   NaN           NaN

[5 rows x 252 columns]

Test Data:
   Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1           NaN          47C                 10B
1                     2           NaN          32D                 30B
2                     3           NaN          99C                 30B
3                     4           NaN           2B                 10A
4                     5           NaN          24D                 30B

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     1/01/09          NaN                NaN
1                               D     1/01/09     270199.0              100.0
2                               I     1/01/09          NaN                NaN
3                               E     1/01/09     280204.0               60.0
4                               B     1/01/09     320502.0               50.0

   RFCD.Code.2  RFCD.Percentage.2  ...  Faculty.No..15  With.PHD.15  \
0          NaN                NaN  ...             NaN          NaN
1          0.0                0.0  ...             NaN          NaN
2          NaN                NaN  ...             NaN          NaN
3     280506.0               20.0  ...             NaN          NaN
4     320703.0               50.0  ...             NaN          NaN

   No..of.Years.in.Uni.at.Time.of.Grant.15  Number.of.Successful.Grant.15  \
0                                      NaN                            NaN
1                                      NaN                            NaN
2                                      NaN                            NaN
3                                      NaN                            NaN
4                                      NaN                            NaN

   Number.of.Unsuccessful.Grant.15  A..15  A.15  B.15  C.15  Unnamed: 251
0                              NaN    NaN   NaN   NaN   NaN           NaN
1                              NaN    NaN   NaN   NaN   NaN           NaN
2                              NaN    NaN   NaN   NaN   NaN           NaN
3                              NaN    NaN   NaN   NaN   NaN           NaN
4                              NaN    NaN   NaN   NaN   NaN           NaN

[5 rows x 252 columns]

## Step 2: Select Key Columns

Next, we select the key columns that are relevant for our analysis and modeling.

In [18]:
# Key columns to use
columns_to_use = [
    'Grant.Application.ID', 'Grant.Status', 'Sponsor.Code', 'Grant.Category.Code',
    'Contract.Value.Band...see.note.A', 'Start.date', 'RFCD.Code.1', 'RFCD.Percentage.1',
    'SEO.Code.1', 'SEO.Percentage.1', 'Person.ID.1', 'Role.1', 'Year.of.Birth.1',
    'Number.of.Successful.Grant.1', 'Number.of.Unsuccessful.Grant.1'
]

train_df = train_df[columns_to_use]
test_df = test_df[[col for col in columns_to_use if col != 'Grant.Status']]  # Test set doesn't have 'Grant.Status'

# Display the updated dataframes
print("Updated Training Data:")
print(train_df.head())
print("\nUpdated Test Data:")
print(test_df.head())

Updated Training Data:
   Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1             1          NaN                 NaN
1                     2             1           2B                 10A
2                     3             1          29A                 10B
3                     4             1          40D                 10B
4                     5             0          59C                 10A

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     8/11/05     280199.0              100.0
1                               B    11/11/05     280103.0               30.0
2                               A    14/11/05     321004.0               60.0
3                               C    15/11/05     270602.0               50.0
4                               A    16/11/05     260500.0               34.0

   SEO.Code.1  SEO.Percentage.1  Person.ID.1                Role.1  \
0    700299.0             100.0      40572.0    CHIEF_INVESTIGATOR
1    700103.0              50.0       9067.0    CHIEF_INVESTIGATOR
2    730105.0              60.0       5967.0    CHIEF_INVESTIGATOR
3    730106.0              70.0      78782.0  PRINCIPAL_SUPERVISOR
4    770199.0             100.0      13042.0    CHIEF_INVESTIGATOR

   Year.of.Birth.1  Number.of.Successful.Grant.1  \
0           1965.0                           0.0
1           1960.0                           0.0
2           1955.0                           0.0
3           1955.0                           0.0
4           1965.0                           0.0

   Number.of.Unsuccessful.Grant.1
0                             0.0
1                             0.0
2                             0.0
3                             0.0
4                             0.0

Updated Test Data:
   Grant.Application.ID Sponsor.Code Grant.Category.Code  \
0                     1          47C                 10B
1                     2          32D                 30B
2                     3          99C                 30B
3                     4           2B                 10A
4                     5          24D                 30B

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     1/01/09          NaN                NaN
1                               D     1/01/09     270199.0              100.0
2                               I     1/01/09          NaN                NaN
3                               E     1/01/09     280204.0               60.0
4                               B     1/01/09     320502.0               50.0

   SEO.Code.1  SEO.Percentage.1  Person.ID.1                Role.1  \
0         NaN               NaN      24017.0  PRINCIPAL_SUPERVISOR
1    780105.0              50.0      67467.0    CHIEF_INVESTIGATOR
2         NaN               NaN       4992.0    CHIEF_INVESTIGATOR
3    610104.0              50.0      39562.0    CHIEF_INVESTIGATOR
4    730104.0             100.0     659757.0    CHIEF_INVESTIGATOR

   Year.of.Birth.1  Number.of.Successful.Grant.1  \
0           1970.0                           4.0
1           1955.0                           5.0
2           1960.0                           0.0
3           1945.0                           4.0
4           1960.0                           2.0

   Number.of.Unsuccessful.Grant.1
0                             2.0
1                             3.0
2                             2.0
3                             0.0
4                             7.0

## Step 3: Convert Columns to Appropriate Data Types

We need to ensure that the numerical columns are properly converted to numeric types.

In [19]:
# Convert numerical columns to numeric types
numerical_cols = ['RFCD.Percentage.1', 'SEO.Percentage.1', 'Year.of.Birth.1', 
                  'Number.of.Successful.Grant.1', 'Number.of.Unsuccessful.Grant.1']

for col in numerical_cols:
    train_df[col] = pd.to_numeric(train_df[col], errors='coerce')
    test_df[col] = pd.to_numeric(test_df[col], errors='coerce')

## Step 4: Handle Missing Values

We handle any missing values in the dataset. For simplicity, we will fill missing values with the mean of the column for numerical columns and with the most frequent value for categorical columns.

In [20]:
# Fill missing values for numerical columns with mean
train_df[numerical_cols] = train_df[numerical_cols].fillna(train_df[numerical_cols].mean())
test_df[numerical_cols] = test_df[numerical_cols].fillna(test_df[numerical_cols].mean())

# Fill missing values for categorical columns with the most frequent value
categorical_cols = ['Sponsor.Code', 'Grant.Category.Code', 'Contract.Value.Band...see.note.A', 
                    'RFCD.Code.1', 'SEO.Code.1', 'Person.ID.1', 'Role.1']

for col in categorical_cols:
    train_df[col] = train_df[col].fillna(train_df[col].mode()[0])
    test_df[col] = test_df[col].fillna(test_df[col].mode()[0])

# Display the dataframes after handling missing values
print("Training Data After Handling Missing Values:")
print(train_df.head())
print("\nTest Data After Handling Missing Values:")
print(test_df.head())

Training Data After Handling Missing Values:
   Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1             1           4D                 10A
1                     2             1           2B                 10A
2                     3             1          29A                 10B
3                     4             1          40D                 10B
4                     5             0          59C                 10A

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     8/11/05     280199.0              100.0
1                               B    11/11/05     280103.0               30.0
2                               A    14/11/05     321004.0               60.0
3                               C    15/11/05     270602.0               50.0
4                               A    16/11/05     260500.0               34.0

   SEO.Code.1  SEO.Percentage.1  Person.ID.1                Role.1  \
0    700299.0             100.0      40572.0    CHIEF_INVESTIGATOR
1    700103.0              50.0       9067.0    CHIEF_INVESTIGATOR
2    730105.0              60.0       5967.0    CHIEF_INVESTIGATOR
3    730106.0              70.0      78782.0  PRINCIPAL_SUPERVISOR
4    770199.0             100.0      13042.0    CHIEF_INVESTIGATOR

   Year.of.Birth.1  Number.of.Successful.Grant.1  \
0           1965.0                           0.0
1           1960.0                           0.0
2           1955.0                           0.0
3           1955.0                           0.0
4           1965.0                           0.0

   Number.of.Unsuccessful.Grant.1
0                             0.0
1                             0.0
2                             0.0
3                             0.0
4                             0.0

Test Data After Handling Missing Values:
   Grant.Application.ID Sponsor.Code Grant.Category.Code  \
0                     1          47C                 10B
1                     2          32D                 30B
2                     3          99C                 30B
3                     4           2B                 10A
4                     5          24D                 30B

  Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  RFCD.Percentage.1  \
0                               A     1/01/09     320702.0          78.330312
1                               D     1/01/09     270199.0         100.000000
2                               I     1/01/09     320702.0          78.330312
3                               E     1/01/09     280204.0          60.000000
4                               B     1/01/09     320502.0          50.000000

   SEO.Code.1  SEO.Percentage.1  Person.ID.1                Role.1  \
0    730108.0         67.219139      24017.0  PRINCIPAL_SUPERVISOR
1    780105.0         50.000000      67467.0    CHIEF_INVESTIGATOR
2    730108.0         67.219139       4992.0    CHIEF_INVESTIGATOR
3    610104.0         50.000000      39562.0    CHIEF_INVESTIGATOR
4    730104.0        100.000000     659757.0    CHIEF_INVESTIGATOR

   Year.of.Birth.1  Number.of.Successful.Grant.1  \
0           1970.0                           4.0
1           1955.0                           5.0
2           1960.0                           0.0
3           1945.0                           4.0
4           1960.0                           2.0

   Number.of.Unsuccessful.Grant.1
0                             2.0
1                             3.0
2                             2.0
3                             0.0
4                             7.0

## Step 5: Feature Engineering

We convert the 'Start.date' column to a datetime format and extract the year from it. We then drop the original 'Start.date' column.

In [21]:
# Convert 'Start.date' to datetime and extract the year
train_df['Start.date'] = pd.to_datetime(train_df['Start.date'], format='%d/%m/%y', errors='coerce')
test_df['Start.date'] = pd.to_datetime(test_df['Start.date'], format='%d/%m/%y', errors='coerce')

train_df['Start.Year'] = train_df['Start.date'].dt.year
test_df['Start.Year'] = test_df['Start.date'].dt.year

# Drop the original 'Start.date' column
train_df.drop('Start.date', axis=1, inplace=True)
test_df.drop('Start.date', axis=1, inplace=True)

# Display the dataframes after feature engineering
print("Training Data After Feature Engineering:")
print(train_df.head())
print("\nTest Data After Feature Engineering:")
print(test_df.head())

Training Data After Feature Engineering:
   Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                     1             1           4D                 10A
1                     2             1           2B                 10A
2                     3             1          29A                 10B
3                     4             1          40D                 10B
4                     5             0          59C                 10A

  Contract.Value.Band...see.note.A  RFCD.Code.1  RFCD.Percentage.1  \
0                               A      280199.0              100.0
1                               B      280103.0               30.0
2                               A      321004.0               60.0
3                               C      270602.0               50.0
4                               A      260500.0               34.0

   SEO.Code.1  SEO.Percentage.1  Person.ID.1                Role.1  \
0    700299.0             100.0      40572.0    CHIEF_INVESTIGATOR
1    700103.0              50.0       9067.0    CHIEF_INVESTIGATOR
2    730105.0              60.0       5967.0    CHIEF_INVESTIGATOR
3    730106.0              70.0      78782.0  PRINCIPAL_SUPERVISOR
4    770199.0             100.0      13042.0    CHIEF_INVESTIGATOR

   Year.of.Birth.1  Number.of.Successful.Grant.1  \
0           1965.0                           0.0
1           1960.0                           0.0
2           1955.0                           0.0
3           1955.0                           0.0
4           1965.0                           0.0

   Number.of.Unsuccessful.Grant.1  Start.Year
0                             0.0        2005
1                             0.0        2005
2                             0.0        2005
3                             0.0        2005
4                             0.0        2005

Test Data After Feature Engineering:
   Grant.Application.ID Sponsor.Code Grant.Category.Code  \
0                     1          47C                 10B
1                     2          32D                 30B
2                     3          99C                 30B
3                     4           2B                 10A
4                     5          24D                 30B

  Contract.Value.Band...see.note.A  RFCD.Code.1  RFCD.Percentage.1  \
0                               A      320702.0          78.330312
1                               D      270199.0         100.000000
2                               I      320702.0          78.330312
3                               E      280204.0          60.000000
4                               B      320502.0          50.000000

   SEO.Code.1  SEO.Percentage.1  Person.ID.1                Role.1  \
0    730108.0         67.219139      24017.0  PRINCIPAL_SUPERVISOR
1    780105.0         50.000000      67467.0    CHIEF_INVESTIGATOR
2    730108.0         67.219139       4992.0    CHIEF_INVESTIGATOR
3    610104.0         50.000000      39562.0    CHIEF_INVESTIGATOR
4    730104.0        100.000000     659757.0    CHIEF_INVESTIGATOR

   Year.of.Birth.1  Number.of.Successful.Grant.1  \
0           1970.0                           4.0
1           1955.0                           5.0
2           1960.0                           0.0
3           1945.0                           4.0
4           1960.0                           2.0

   Number.of.Unsuccessful.Grant.1  Start.Year
0                             2.0        2009
1                             3.0        2009
2                             2.0        2009
3                             0.0        2009
4                             7.0        2009